### ISSUE TITLE
[BUG] problems displaying agent recordings in quickstart.ipynb notebook

### ISSUE THREAD

**Issue by doesburg11** [instadeepai/Mava#873] opened 2023-01-11 14:47 UTC
### Describe the bug

Problems when trying to run the quickstart.ipynb notebook: 

Agent recordings in section 5. of the notebook  ("View agent recordings")  are not showing up ("Check if any agent recordings are available." ) and therefore the latest recording cannot be displayed in the next cell ("View the latest agent recording").

FYI: This problem did not arise until around 15 October 2022, when this was the last time agent recordings were saved correctly in my experimentation. Since then however,  I am not able to detect any agent recordings at all anymore. (obviously also not after waiting sufficiently). I've repeatedly tried since then (including after recent box-2d and numpy fixes in the notebook), but to no avail unfortunately.

### To Reproduce
1.  Visit https://colab.research.google.com/github/instadeepai/Mava/blob/develop/examples/quickstart.ipynb
2.  Run all cells. (BTW: "4. Visuallise our training results using Tensorboard" works fine)

Result: No  saved agent recordings

### Expected behavior

Saved agent recordings like for example "agents_3_eval_episode.html" 

### Context (Environment)
 - OS: Google Colab – Release 2022/12/6

### Additional context
Worked fine before 2022/10/15. Failed afterwards. Same in Colab Pro.

### Possible Solution
It is tempting to speculate about a changed configuration in Colab. Note however that the bug already appeared before the Colab migration to Python 3.8 from 2022/12/6.

**Comment by OmaymaMahjoub** [comment] 2023-01-13 12:12
Hello @doesburg11, thank you for bringing to our attention that the  displaying recording is not working in the quickstart example. We are currently investigating the issue, which appears to be related to a problem with recording the agents. Specifically, the folder that should contain the recordings, located at /root/mava/{mava_id}/recordings/, is consistently empty. We will update you as soon as we have more information and a solution to this issue.:slightly_smiling_face:

**Comment by OmaymaMahjoub** [comment] 2023-01-13 12:49
The problem was primarily caused by the improper use of the pyglet library. We have corrected it in this [pull request](https://github.com/instadeepai/Mava/pull/875) and once it is merged, you will be able to display the recordings of the agents again :tada:

**Closed** 2023-01-18 14:31 UTC
Labels: bug

**Comment by doesburg11** [comment] 2023-01-18 17:43
Thank you very much @OmaymaMahjoub . Issue resolved! :)
